FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app

COPY pom.xml ./
COPY src ./src

RUN mvn -B -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app

COPY --from=build /app/target/user-service-0.0.1-SNAPSHOT.jar /app/user-service.jar

EXPOSE 9090

ENTRYPOINT ["java", "-jar", "/app/user-service.jar"]
